In [6]:
import pandas as pd
from sqlalchemy import create_engine
df=pd.read_excel("../Data/churn.xlsx")

In [7]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Churn,Churn.1,Active,Age Group
0,1,15565701,Ferri,698,Spain,Female,39,9,161993.89,1,0,0,90212.38,0,NaN,No-Churn,Not Active,35-45
1,2,15565706,Akobundu,612,Spain,Male,35,1,0.00,1,1,1,83256.26,1,Churn,NaN,Active,35-45
2,3,15565714,Cattaneo,601,France,Male,47,1,64430.06,2,0,1,96517.97,0,NaN,No-Churn,Active,45+
3,4,15565779,Kent,627,Germany,Female,30,6,57809.32,1,1,0,188258.49,0,NaN,No-Churn,Not Active,25-35
4,5,15565796,Docherty,745,Germany,Male,48,10,96048.55,1,1,0,74510.65,0,NaN,No-Churn,Not Active,45+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15815628,Moysey,711,France,Female,37,8,113899.92,1,0,0,80215.20,0,NaN,No-Churn,Not Active,35-45
9996,9997,15815645,Akhtar,481,France,Male,37,8,152303.66,2,1,1,175082.20,0,NaN,No-Churn,Active,35-45
9997,9998,15815656,Hopkins,541,Germany,Female,39,9,100116.67,1,1,1,199808.10,1,Churn,NaN,Active,35-45
9998,9999,15815660,Mazzi,758,France,Female,34,1,154139.45,1,1,1,60728.89,0,NaN,No-Churn,Active,25-35
9999,10000,15815690,Akabueze,614,Spain,Female,40,3,113348.50,1,1,1,77789.01,0,NaN,No-Churn,Active,35-45

In [8]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Churn,Churn.1,Active,Age Group
0,1,15565701,Ferri,698,Spain,Female,39,9,161993.89,1,0,0,90212.38,0,NaN,No-Churn,Not Active,35-45
1,2,15565706,Akobundu,612,Spain,Male,35,1,0.00,1,1,1,83256.26,1,Churn,NaN,Active,35-45
2,3,15565714,Cattaneo,601,France,Male,47,1,64430.06,2,0,1,96517.97,0,NaN,No-Churn,Active,45+
3,4,15565779,Kent,627,Germany,Female,30,6,57809.32,1,1,0,188258.49,0,NaN,No-Churn,Not Active,25-35
4,5,15565796,Docherty,745,Germany,Male,48,10,96048.55,1,1,0,74510.65,0,NaN,No-Churn,Not Active,45+

In [9]:
df.isnull().sum()

RowNumber             0
CustomerId            0
Surname               0
CreditScore           0
Geography             0
Gender                0
Age                   0
Tenure                0
Balance               0
NumOfProducts         0
HasCrCard             0
IsActiveMember        0
EstimatedSalary       0
Exited                0
Churn              7963
Churn.1            2037
Active                0
Age Group             0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
Churn               object
Churn.1             object
Active              object
Age Group           object
dtype: object

In [12]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Churn', 'Churn.1',
       'Active ', 'Age Group'],
      dtype='object')

In [13]:
df.drop(columns=("Active "),inplace=True)

In [14]:
df.columns=df.columns.str.replace(" ","_")

In [15]:
engine=create_engine(
    "mysql+pymysql://root:password@localhost/testd"
)

In [16]:
df.to_sql(
"churn",
con=engine,
if_exists="replace",
index=False
)

10000